### ISSUE TITLE
Change font style and delete scroll bars for Chrome on Windows

### ISSUE THREAD

**Issue by sofmal** [ArchitudeSweden/FileMaker_Utility#44]
![image](https://user-images.githubusercontent.com/31207156/43278455-14fc7f64-9103-11e8-8f1d-706bef269e99.png)

**Comment by SofiaMalmsten** [comment]
Scroll bars are deleted where we don't want them. The font style depends on if the computer has the font installed or not. We will keep Avenir for now.
